#!/usr/bin/env python3
"""
Constancy's lookup tables, worked out once on a computer and written into
src/TableData.h.

    python3 tools/tables/make_tables.py

The RP2040 has no floating-point unit, so the card never calculates a sine,
an exponential or a tanh while it plays: it looks them up in these tables
and blends between neighbouring entries. Making them here, rather than at
power-on, means the card doesn't need floating point at all.
"""
import math
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "src", "TableData.h")
SAMPLE_RATE = 48000
SINE_SIZE = 1024
SHAPE_STEPS = 512
CUTOFF_TOP = 135  # MIDI note 135, about 20kHz


def note_hz(n):
    return 440.0 * 2 ** ((n - 69) / 12)


def array(w, ctype, name, values, per_line=12, comment=None):
    if comment:
        for line in comment:
            w(f"// {line}")
    w(f"inline constexpr {ctype} {name}[{len(values)}] = {{")
    for i in range(0, len(values), per_line):
        w("\t" + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    w("};")
    w("")


def main():
    lines = []
    w = lines.append
    w("// Generated by tools/tables/make_tables.py -- don't edit by hand; edit and rerun that.")
    w("#pragma once")
    w("#include <cstdint>")
    w("")
    w("namespace constancy")
    w("{")
    w("namespace table")
    w("{")
    w("")

    sine = [round(32767 * math.sin(2 * math.pi * i / SINE_SIZE)) for i in range(SINE_SIZE + 1)]
    array(w, "int16_t", "sine", sine, comment=[
        "One cycle of a sine wave, +/-32767, plus a copy of the first point at",
        "the end so interpolation never has to wrap."])

    inc = [int(note_hz(n) * 2 ** 32 / SAMPLE_RATE) for n in range(128)]
    array(w, "uint32_t", "noteInc", [f"{v}u" for v in inc], per_line=8, comment=[
        "How far a 32-bit phase moves per sample for each MIDI note (A4 = 440Hz)."])

    exp2 = [round(65536 * 2 ** (i / 32)) for i in range(33)]
    array(w, "int32_t", "exp2", exp2, per_line=11, comment=["2^(i/32) for i = 0..32, Q16."])

    log2 = [round(4096 * math.log2(1 + i / 32)) for i in range(33)]
    array(w, "int32_t", "log2", log2, per_line=11, comment=["log2(1 + i/32) for i = 0..32, Q12."])

    cutoff = []
    for n in range(CUTOFF_TOP + 1):
        c = 1 - math.exp(-2 * math.pi * note_hz(n) / SAMPLE_RATE)
        cutoff.append(min(32767, round(32767 * c)))
    array(w, "int16_t", "cutoff", cutoff, comment=[
        "One-pole filter coefficients (Q15) for a cutoff at each MIDI note pitch,",
        f"0 (8Hz) to {CUTOFF_TOP} (20kHz): how far the filter moves towards its input",
        "each sample, 1 - e^(-2 pi f / 48000)."])

    xs = [8 * i / SHAPE_STEPS - 4 for i in range(SHAPE_STEPS + 1)]

    def softclip(x):
        a = abs(x)
        s = a if a <= 0.5 else 1 - 0.25 / a
        return math.copysign(s, x)

    array(w, "int16_t", "softClip", [round(32767 * softclip(x)) for x in xs], comment=[
        "SuperCollider's softclip, Icarus's loop clipper: straight up to 0.5, then",
        "bending smoothly towards 1. Inputs from -4 to +4 (full scale is 1) in 512",
        "steps, out to +/-32767."])

    w("} // namespace table")
    w("} // namespace constancy")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
