// Hand-merge tool for free-text metadata values (tags, Language, Status).
//
//   npm run metadata-values -- report [FILE]            write a merge sheet
//   npm run metadata-values -- apply [FILE] [--dry-run] rewrite info.yaml files
//
// `report` lists every value in use, mapped to itself, with similar spellings
// grouped together. Edit the right-hand values, then `apply` renames them in
// every releases/*/info.yaml. Edits are spliced into the original text so the
// rest of each file (comments, quoting, layout) is left untouched.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';
import { normalizeYamlKey } from '../utils/strings.js';
import { VALUE_FIELDS, collectKnownValues, groupSimilar } from '../utils/similarValues.js';
import { readReleaseInfos } from '../validate/knownValues.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../../..');
const RELEASES_DIR = path.join(ROOT, 'releases');
const DEFAULT_SHEET = path.join(ROOT, 'metadata-values.yml');

/** `value` as YAML text: plain when it round-trips unchanged, else double-quoted. */
function yamlText(value) {
  const text = String(value);
  try {
    if (text.trim() === text && !text.includes(' #') && YAML.parse(`- ${text}`)?.[0] === text) return text;
  } catch {
    // Fall through to quoting.
  }
  return JSON.stringify(text);
}

/** Replacement text for a scalar, keeping the original quote style where possible. */
function scalarText(value, original) {
  if (original.startsWith('"')) return JSON.stringify(String(value));
  if (original.startsWith("'")) return `'${String(value).replace(/'/g, "''")}'`;
  return yamlText(value);
}

/** Render the editable merge sheet for `known` (from collectKnownValues). */
export function renderSheet(known) {
  const lines = [
    '# Metadata value merge sheet, generated by `npm run metadata-values -- report`.',
    '#',
    '# Each value currently used in releases/*/info.yaml is mapped to itself.',
    '# Change the right-hand side to rename it on every card that uses it; for',
    '# tags, use ~ to remove the tag. Unchanged lines are ignored.',
    '# Values listed under "similar" look like spellings of the same thing.',
    '#',
    '# Preview with `npm run metadata-values -- apply --dry-run`, then run it',
    '# without --dry-run to rewrite the files.',
  ];
  for (const field of VALUE_FIELDS) {
    const index = known[field.key] || {};
    const uses = value => index[value].length;
    const byUse = (a, b) => uses(b) - uses(a) || a.localeCompare(b);
    const groups = groupSimilar(Object.keys(index).sort((a, b) => a.localeCompare(b)));
    const similar = groups.filter(group => group.length > 1);
    const single = groups.filter(group => group.length === 1).flat();
    const entry = value => {
      const ids = index[value];
      const cards = ids.length > 4 ? `${ids.slice(0, 4).join(', ')}, …` : ids.join(', ');
      return `  ${yamlText(value)}: ${yamlText(value)}  # ${ids.length} card${ids.length === 1 ? '' : 's'}: ${cards}`;
    };
    lines.push('', `${field.key}:`);
    for (const group of similar) {
      lines.push('  # similar');
      lines.push(...group.sort(byUse).map(entry), '');
    }
    if (similar.length && single.length) lines.push('  # other values');
    lines.push(...single.map(entry));
  }
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}

/**
 * Parse an edited sheet into `{ [field.key]: Map(oldValue -> newValue|null) }`,
 * keeping only entries that change something.
 */
export function parseSheet(text) {
  const raw = YAML.parse(text) || {};
  const out = {};
  for (const field of VALUE_FIELDS) {
    const entries = raw[field.key];
    const changes = new Map();
    if (entries != null && (typeof entries !== 'object' || Array.isArray(entries))) {
      throw new Error(`${field.key} should be a mapping of old value: new value.`);
    }
    for (const [from, to] of Object.entries(entries || {})) {
      if (to === null) {
        if (!field.list) throw new Error(`${field.key} "${from}" cannot be removed (the field is required); map it to a value.`);
        changes.set(from, null);
        continue;
      }
      if (typeof to === 'object') throw new Error(`${field.key} "${from}" should map to a single value.`);
      const next = String(to).trim();
      if (!next) throw new Error(`${field.key} "${from}" maps to an empty value.`);
      if (next !== from) changes.set(from, next);
    }
    out[field.key] = changes;
  }
  return out;
}

/**
 * Apply sheet changes to one info.yaml source. Returns `{ source, changes }`
 * where `changes` lists human-readable edits; `source` is unchanged if none.
 */
export function applySheet(source, sheet) {
  const document = YAML.parseDocument(source);
  if (document.errors.length || !YAML.isMap(document.contents)) return { source, changes: [] };
  const edits = [];
  const changes = [];
  const remap = (field, value) => (sheet[field.key]?.has(value) ? sheet[field.key].get(value) : value);

  for (const field of VALUE_FIELDS) {
    if (!sheet[field.key]?.size) continue;
    const pair = document.contents.items.find(item => normalizeYamlKey(item.key?.value) === normalizeYamlKey(field.key));
    const node = pair?.value;
    if (!node?.range) continue;

    if (YAML.isScalar(node) && !field.list) {
      const value = String(node.value ?? '').trim();
      const next = remap(field, value);
      if (next === value) continue;
      edits.push({ start: node.range[0], end: node.range[1], text: scalarText(next, source.slice(node.range[0], node.range[1])) });
      changes.push(`${field.key}: "${value}" → "${next}"`);
      continue;
    }

    if (!field.list) continue;
    const items = YAML.isSeq(node) ? node.items : null;
    const values = items
      ? items.map(item => (YAML.isScalar(item) ? String(item.value ?? '').trim() : null))
      : String(node.value ?? '').split(',').map(value => value.trim()).filter(Boolean);
    const seen = new Set();
    const result = values.map(value => {
      if (value == null) return { keep: true, value };
      const next = remap(field, value);
      if (next === null || seen.has(next)) return { keep: false, value, next };
      seen.add(next);
      return { keep: true, value, next };
    });
    const touched = result.filter(item => item.value != null && (!item.keep || item.next !== item.value));
    if (!touched.length) continue;
    for (const item of touched) {
      if (!item.keep && item.next === null) changes.push(`${field.key}: removed "${item.value}"`);
      else if (!item.keep && item.next === item.value) changes.push(`${field.key}: removed duplicate "${item.value}"`);
      else if (!item.keep) changes.push(`${field.key}: "${item.value}" → "${item.next}" (already present, dropped)`);
      else changes.push(`${field.key}: "${item.value}" → "${item.next}"`);
    }
    const kept = result.filter(item => item.keep && item.value != null).map(item => item.next);

    if (!items) {
      // Comma-separated string form.
      edits.push({ start: node.range[0], end: node.range[1], text: scalarText(kept.join(', '), source.slice(node.range[0], node.range[1])) });
    } else if (node.flow || !kept.length) {
      const others = result.filter(item => item.value == null).length;
      if (others) continue; // Non-scalar entries: leave for a human.
      edits.push({ start: node.range[0], end: node.range[1], text: `[${kept.map(yamlText).join(', ')}]` });
    } else {
      items.forEach((item, i) => {
        const outcome = result[i];
        if (outcome.value == null) return;
        if (!outcome.keep) {
          // Drop the whole "- value" line.
          const lineStart = source.lastIndexOf('\n', item.range[0] - 1) + 1;
          const newline = source.indexOf('\n', item.range[1]);
          edits.push({ start: lineStart, end: newline === -1 ? source.length : newline + 1, text: '' });
        } else if (outcome.next !== outcome.value) {
          edits.push({ start: item.range[0], end: item.range[1], text: scalarText(outcome.next, source.slice(item.range[0], item.range[1])) });
        }
      });
    }
  }

  if (!edits.length) return { source, changes: [] };
  let out = source;
  for (const edit of edits.sort((a, b) => b.start - a.start)) {
    out = out.slice(0, edit.start) + edit.text + out.slice(edit.end);
  }
  return { source: out, changes };
}

function report(file) {
  const known = collectKnownValues(readReleaseInfos(RELEASES_DIR));
  fs.writeFileSync(file, renderSheet(known));
  const counts = VALUE_FIELDS.map(field => `${Object.keys(known[field.key]).length} ${field.key}`).join(', ');
  console.log(`Wrote ${path.relative(ROOT, file) || file} (${counts}).`);
  console.log('Edit the right-hand values, then run `npm run metadata-values -- apply --dry-run`.');
}

function apply(file, dryRun) {
  if (!fs.existsSync(file)) throw new Error(`${file} not found. Run \`npm run metadata-values -- report\` first.`);
  const sheet = parseSheet(fs.readFileSync(file, 'utf8'));
  const total = Object.values(sheet).reduce((n, changes) => n + changes.size, 0);
  if (!total) {
    console.log('The sheet has no changes.');
    return;
  }
  const infos = readReleaseInfos(RELEASES_DIR);
  const known = collectKnownValues(infos);
  for (const field of VALUE_FIELDS) {
    for (const from of sheet[field.key].keys()) {
      if (!known[field.key][from]) console.warn(`warning: ${field.key} "${from}" is not used by any card.`);
    }
  }
  let changedFiles = 0;
  for (const info of infos) {
    const result = applySheet(info.source, sheet);
    if (!result.changes.length) continue;
    changedFiles++;
    console.log(`${path.relative(ROOT, info.file)}\n  ${result.changes.join('\n  ')}`);
    if (!dryRun) fs.writeFileSync(info.file, result.source);
  }
  console.log(`${dryRun ? 'Would update' : 'Updated'} ${changedFiles} file(s).`);
}

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const [command, fileArg] = args.filter(arg => arg !== '--dry-run');
  // npm --prefix runs scripts from tools/sitegen; resolve against where npm was run.
  const file = fileArg ? path.resolve(process.env.INIT_CWD || process.cwd(), fileArg) : DEFAULT_SHEET;
  if (command === 'report') report(file);
  else if (command === 'apply') apply(file, dryRun);
  else {
    console.error('Usage: npm run metadata-values -- report [FILE]\n       npm run metadata-values -- apply [FILE] [--dry-run]');
    process.exitCode = 2;
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (error) {
    console.error(`error: ${error.message}`);
    process.exitCode = 1;
  }
}
