#!/usr/bin/env python3
import argparse
import datetime as _datetime
import os
import re
import struct
import subprocess
import sys


SAMPLE_RATE = 48000
CHANNELS = 2
BYTES_PER_SAMPLE = 2


def run_sox(input_path):
    cmd = [
        "sox",
        input_path,
        "-r",
        str(SAMPLE_RATE),
        "-c",
        str(CHANNELS),
        "-b",
        "16",
        "-e",
        "signed-integer",
        "-L",
        "-t",
        "raw",
        "-",
        "gain",
        "-n",
        "-3",
    ]
    try:
        return subprocess.check_output(cmd)
    except FileNotFoundError:
        print("error: sox is required to encode breaky audio", file=sys.stderr)
        raise SystemExit(1)
    except subprocess.CalledProcessError as exc:
        print("error: sox failed while encoding audio", file=sys.stderr)
        if exc.output:
            print(exc.output.decode("utf-8", errors="replace"), file=sys.stderr)
        raise SystemExit(exc.returncode)


def clamp12(value):
    if value < -2048:
        return -2048
    if value > 2047:
        return 2047
    return value


def sign_to_12bit(value):
    return value & 0x0FFF


def pack_frame(left, right):
    left12 = sign_to_12bit(clamp12(left >> 4))
    right12 = sign_to_12bit(clamp12(right >> 4))
    return (
        left12 & 0xFF,
        ((left12 >> 8) & 0x0F) | ((right12 & 0x0F) << 4),
        (right12 >> 4) & 0xFF,
    )


def encode(raw):
    frame_size = CHANNELS * BYTES_PER_SAMPLE
    if len(raw) % frame_size != 0:
        raise ValueError("raw audio length is not an even number of stereo frames")

    packed = bytearray()
    peak = 0
    frame_count = len(raw) // frame_size
    for index in range(frame_count):
        offset = index * frame_size
        left, right = struct.unpack_from("<hh", raw, offset)
        peak = max(peak, abs(left), abs(right))
        packed.extend(pack_frame(left, right))
    return packed, frame_count, peak


def infer_bpm(input_path):
    match = re.search(r"bpm[_-]?(\d+(?:\.\d+)?)", os.path.basename(input_path), re.IGNORECASE)
    if not match:
        return None
    bpm = round(float(match.group(1)))
    if bpm <= 0:
        return None
    return bpm


def write_header(output_path, input_path, source_bpm, packed, frame_count, peak):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    generated = _datetime.datetime.now(_datetime.timezone.utc).isoformat()
    with open(output_path, "w", encoding="utf-8") as out:
        out.write("// Generated by scripts/encode_audio.py. Do not edit by hand.\n")
        out.write(f"// Source: {input_path}\n")
        out.write(f"// Generated: {generated}\n")
        out.write("#pragma once\n\n")
        out.write("#include <stdint.h>\n")
        out.write("#include \"pico/platform.h\"\n\n")
        out.write(f"#define BREAKY_SAMPLE_RATE {SAMPLE_RATE}u\n")
        out.write(f"#define BREAKY_SOURCE_BPM {source_bpm}u\n")
        out.write(f"#define BREAKY_FRAME_COUNT {frame_count}u\n")
        out.write(f"#define BREAKY_AUDIO_BYTES {len(packed)}u\n")
        out.write(f"#define BREAKY_SOURCE_PEAK_16BIT {peak}u\n\n")
        out.write(
            "static const uint8_t __in_flash(\"breaky_audio\") "
            "breaky_audio_data[BREAKY_AUDIO_BYTES] = {\n"
        )
        for i in range(0, len(packed), 18):
            chunk = packed[i : i + 18]
            out.write("    ")
            out.write(", ".join(f"0x{byte:02x}" for byte in chunk))
            if i + len(chunk) < len(packed):
                out.write(",")
            out.write("\n")
        out.write("};\n")


def main():
    parser = argparse.ArgumentParser(description="Encode Breaky audio as packed 12-bit stereo.")
    parser.add_argument("--bpm", type=float, help="source audio BPM; defaults to inferring bpmNNN from filename")
    parser.add_argument("input")
    parser.add_argument("output")
    args = parser.parse_args()

    source_bpm = round(args.bpm) if args.bpm is not None else infer_bpm(args.input)
    if source_bpm is None:
        print("error: source BPM not provided and could not infer bpmNNN from filename", file=sys.stderr)
        raise SystemExit(1)
    if source_bpm <= 0:
        print("error: source BPM must be positive", file=sys.stderr)
        raise SystemExit(1)

    raw = run_sox(args.input)
    packed, frame_count, peak = encode(raw)
    write_header(args.output, args.input, source_bpm, packed, frame_count, peak)
    seconds = frame_count / SAMPLE_RATE
    print(
        f"encoded {frame_count} stereo frames ({seconds:.2f}s), "
        f"{len(packed)} bytes, source bpm {source_bpm}, source peak {peak}/32767"
    )


if __name__ == "__main__":
    main()
