export const infoYamlSchema = {
  id: 'workshop-computer-info-yaml',
  version: 1,
  source: 'documentation/info.yaml.md',
  fields: [
    { path: 'draft', type: 'boolean', required: false, description: 'Metadata review state.' },
    { path: 'Name', type: 'string', required: true, aliases: ['Title'], description: 'Display title for the card.' },
    { path: 'Description', type: 'string', required: true, description: 'Short summary for the card.' },
    { path: 'Language', type: 'string', required: true, description: 'Implementation language or stack.' },
    { path: 'Creator', type: 'string', required: true, description: 'Author or maintainer.' },
    { path: 'Version', type: 'string', required: true, description: 'Release or firmware version.' },
    { path: 'Status', type: 'string', required: true, description: 'Release status.' },
    { path: 'License', type: 'string', required: false, description: 'SPDX identifier or short license name.' },
    { path: 'date', type: 'string', required: false, aliases: ['releasedate'], description: 'Last update date in YYYY-MM-DD form.' },
    { path: 'contact', type: 'object', required: false, description: 'Contact metadata.' },
    { path: 'Editor', type: 'string', required: false, description: 'Web editor mode or URL.' },
    { path: 'web-entry', type: 'string', required: false, description: 'Web editor entry HTML file.' },
    { path: 'repository', type: 'string', required: false, description: 'Upstream source repository.' },
    { path: 'tags', type: 'array|string', required: false, description: 'Discovery tags.' },
    { path: 'demo-link', type: 'string', required: false, description: 'Demo video URL.' },
    { path: 'audio-sample', type: 'array|string', required: false, description: 'Demo audio sample(s): a repo-relative file path, a SoundCloud URL, a Bandcamp EmbeddedPlayer URL, or a list of these.' },
    { path: 'manual', type: 'string', required: false, description: 'Abbreviated operator summary.' },
    { path: 'panel', type: 'object', required: false, description: 'Panel jack metadata.' },
    { path: 'controls', type: 'object', required: false, description: 'Control metadata.' },
    { path: 'host', type: 'object', required: false, description: 'Host connectivity metadata.' },
    { path: 'switch_modes', type: 'object', required: false, description: 'Legacy switch mode descriptions.' },
    { path: 'notes', type: 'array|string', required: false, description: 'Supplementary notes.' },
    { path: 'documentation', type: 'object', required: false, description: 'Structured documentation sections.' },
    { path: 'quick_start', type: 'array', required: false, description: 'Quick-start checklist.' },
    { path: 'videos', type: 'array', required: false, description: 'Structured video links.' },
    { path: 'memory', type: 'object', required: false, description: 'Card memory requirements.' },
    { path: 'uf2', type: 'array', required: false, description: 'Curated firmware download list; when present it overrides auto-discovery. Each item needs a path OR a download.url: { path?, name?, download?: { url, sha256 } }.' },
  ],
};