export const infoYamlSchema = {
  id: 'workshop-computer-info-yaml',
  version: 2,
  source: 'documentation/info.yaml.md',
  fields: [
    { path: 'draft', type: 'boolean', required: false, description: 'Metadata review state.' },
    { path: 'Name', type: 'string', required: true, aliases: ['Title'], description: 'Display title for the card.' },
    { path: 'short-description', type: 'string', required: true, description: 'Concise catalog tagline shown in discovery views.' },
    { path: 'summary', type: 'string', required: true, description: 'Operator overview shown in the card detail header.' },
    { path: 'Language', type: 'string', required: true, description: 'Implementation language or stack.' },
    { path: 'Creator', type: 'string', required: true, description: 'Author or maintainer.' },
    { path: 'Version', type: 'string', required: true, description: 'Release or firmware version.' },
    { path: 'Status', type: 'string', required: true, description: 'Release status.' },
    { path: 'License', type: 'string', required: false, description: 'SPDX identifier or short license name.' },
    { path: 'date', type: 'string', required: false, aliases: ['releasedate'], description: 'Last update date in YYYY-MM-DD form.' },
    { path: 'contact', type: 'object', required: false, description: 'Contact metadata.' },
    { path: 'Editor', type: 'string', required: false, description: 'Web editor mode or URL.' },
    { path: 'web-entry', type: 'string', required: false, description: 'Web editor entry HTML file.' },
    { path: 'repository', type: 'string', required: false, description: 'Upstream source repository.' },
    { path: 'discussion', type: 'string', required: false, description: 'Card-specific feedback or discussion URL, such as a Discord thread.' },
    { path: 'tags', type: 'array|string', required: false, description: 'Discovery tags.' },
    { path: 'demo-link', type: 'string', required: false, description: 'Demo video URL.' },
    { path: 'audio-sample', type: 'array|string', required: false, description: 'Demo audio sample(s): a repo-relative file path, a SoundCloud URL, a Bandcamp EmbeddedPlayer URL, or a list of these.' },
    { path: 'readme', type: 'string', required: false, description: 'Full inline README in Markdown; replaces the rendered README.md section.' },
    { path: 'panel', type: 'object', required: false, description: 'Panel jack metadata. Unconditioned entries form the base; when.z up/middle/down entries override it for that switch position.' },
    { path: 'controls', type: 'object', required: false, description: 'Control metadata. Switch keys are up/middle/down plus the tap action; when.z supports only up/middle/down.' },
    { path: 'host', type: 'object', required: false, description: 'Host connectivity metadata.' },
    { path: 'uf2', type: 'array', required: false, description: 'Curated firmware download list; when present it overrides auto-discovery. Each item needs a path OR a download.url: { path?, name?, download?: { url, sha256 } }.' },
  ],
};